name: Build and Package WPF Application

on:
  push:
    branches:
      - release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' TestApp/TestApp/TestApp.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Echo Version
        run: echo "The version is ${{ steps.get-version.outputs.version }}"

      - name: Publish .NET project
        run: dotnet publish -c Release --self-contained -r win-x64 -o .\publish

      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/squidgy617/UpdaterTest
          vpk pack --packId WpfVelopack --packVersion ${{ steps.get-version.outputs.version }} --packDir publish --mainExe TestApp.exe --packTitle TestApp
          vpk upload github --repoUrl https://github.com/squidgy617/UpdaterTest --publish --releaseName "TestApp ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
